# paramètre personaliser pour mon site web (local)
port: 8080
host: lopos
livereload: true
watch: true
profile: true
encoding: utf-8
incremental: true
Source: ./
Destination: ./_site

collections:
  authors:
    output: true

defaults:
  - 
    scope:
      path: "authors"
    values:
      layout: "auteur"
  - 
    scope:
      path: "posts"
    values:
      layout: "post"
  - 
    scope:
      path: "" # une chaîne vide signifie tous les fichiers du projet
    values:
      layout: "default"

# pour tout les fichiers à ne pas construire (non-build)
exclude:
  - README.md
  - .jekyll-cache/*
  - .jekyll-metadata

